# Imagen base de Python administrada por Microsoft [cite: 17]
FROM mcr.microsoft.com/devcontainers/python:3.11

# Instalación de herramientas de sistema (htop y tree) [cite: 18]
RUN apt-get update && apt-get install -y htop tree
